# Select backend
file(WRITE ${CMAKE_BINARY_DIR}/select_backend.c "/* select_backend.c generated by CMake */\n")
if (UNIX)
	file(APPEND ${CMAKE_BINARY_DIR}/select_backend.c "#include \"${CMAKE_SOURCE_DIR}/psh/backends/posix.c\"\n")
else()
	message(FATAL_ERROR "Currently unsupported host system: " ${CMAKE_SYSTEM})
endif()